# Generated by Django 3.1.3 on 2020-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=465)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email_from', models.CharField(max_length=50)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(blank=True)),
                ('last_update', models.DateTimeField(blank=True)),
                ('sent', models.IntegerField(blank=True)),
            ],
        ),
    ]
