# Generated by Django 3.1.3 on 2020-11-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
