# Generated by Django 3.1.3 on 2020-11-16 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mailbox_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, size=256),
        )
    ]
