# Generated by Django 3.1.3 on 2020-11-16 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201116_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, null=True, size=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, null=True, size=256),
        ),
    ]
