# Generated by Django 3.1.3 on 2020-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201116_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
